### ISSUE TITLE
Phase 2

### ISSUE THREAD

**Issue by misoxxx** [misoxxx/sparse#1]
## Goals
- [x] __Configure Github Actions to run tests__
    - Choose a suitable performance metric
- [x]  __Start the implementation__
    - Standard library, regexes, json parser
    - We should be able to parse
        - [x] Title #7
        - [x] Versions #8
        - [x] Bibliography #9
- [x] __Write 2xA4 report, prepare 5min overview for seminar__
    - Project design
    - Current progress
    - Encountered obstacles

**Comment by ondrys123** [comment]
## Goals
- [ ] __Configure Github Actions to run tests__
* Choose a suitable performance metric

<br/>

 - [ ]  __Start the implementation__
* Standard library, regexes, json parser
* We should be able to parse
     * [ ] title  
     * [ ]  versions
     * [ ] bibliography

<br/>

- [ ] __Write 2xA4 report, prepare 5min overview for seminar__
* Project design
* Current progress
* Encountered obstacles

**Comment by ondrys123** [comment]
Phase II finished
